===== Week 4 =====

10/10/2020

I created a function, 'delete_image_post' in general_user.py to implement the databse backend 
side of deleting user posts. Some strange behaviour by my dev enviroment led to the images
table in the database being deleted. The function which takes image_id as an argument 
does not seem to recieve the image_id correctly from the function argument and when you
manually insert the integer post id to delete, it works. The test file i wrote is
simply opening a connection and calling the function with a predefine value, but for some
reason the argument is not being passed properly and is the value 10 regardless of what,
value the function is called with. I will instal windows and the linux subsystem on my computer
rather than continuning to use Macosx as this strange behabiour may be solved. I do belive though
that the function is correct, and hence was pushed to my branch db-functions.
